"""cria tabelas do sistema de reservas

Revision ID: df0746c5a6fc
Revises: 001
Create Date: 2026-08-25 23:25:04.499336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df0746c5a6fc'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('limite_territorial', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comodidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('servicos_adicionais',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('preco >= 0', name='ck_servicos_preco'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hoteis',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cidade_id', sa.UUID(), nullable=False),
    sa.Column('categoria_estrelas', sa.Integer(), nullable=False),
    sa.Column('localizacao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('categoria_estrelas BETWEEN 1 AND 5', name='ck_hoteis_categoria_estrelas'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_comodidades',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('comodidade_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comodidade_id'], ['comodidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id', 'comodidade_id')
    )
    op.create_table('quartos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('preco_diaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_adultos', sa.Integer(), nullable=False),
    sa.Column('max_criancas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('max_adultos >= 1', name='ck_quartos_max_adultos'),
    sa.CheckConstraint('max_criancas >= 0', name='ck_quartos_max_criancas'),
    sa.CheckConstraint('preco_diaria >= 0', name='ck_quartos_preco_diaria'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'numero', name='uq_quartos_hotel_numero')
    )
    op.create_table('tarifas_temporada',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('multiplicador', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_tarifas_data'),
    sa.CheckConstraint('multiplicador > 0', name='ck_tarifas_multiplicador'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('quarto_id', sa.UUID(), nullable=False),
    sa.Column('data_checkin', sa.Date(), nullable=False),
    sa.Column('data_checkout', sa.Date(), nullable=False),
    sa.Column('quantidade_adultos', sa.Integer(), nullable=False),
    sa.Column('quantidade_criancas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quantidade_bebes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('early_checkin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('late_checkout', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('necessita_berco', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tarifa_tipo', sa.String(length=20), server_default=sa.text("'Reembolsavel'"), nullable=False),
    sa.Column('data_limite_cancelamento', sa.Date(), nullable=True),
    sa.Column('valor_multa_cancelamento', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'Pendente'"), nullable=False),
    sa.CheckConstraint("status IN ('Pendente', 'Confirmada', 'Cancelada')", name='ck_reservas_status'),
    sa.CheckConstraint("tarifa_tipo IN ('Reembolsavel', 'Nao Reembolsavel')", name='ck_reservas_tarifa_tipo'),
    sa.CheckConstraint('data_checkout > data_checkin', name='ck_reservas_datas'),
    sa.CheckConstraint('quantidade_adultos >= 1', name='ck_reservas_adultos'),
    sa.CheckConstraint('quantidade_bebes >= 0', name='ck_reservas_bebes'),
    sa.CheckConstraint('quantidade_criancas >= 0', name='ck_reservas_criancas'),
    sa.CheckConstraint('valor_multa_cancelamento >= 0', name='ck_reservas_valor_multa'),
    sa.CheckConstraint('valor_total >= 0', name='ck_reservas_valor_total'),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('nota BETWEEN 1 AND 5', name='ck_avaliacoes_nota'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id')
    )
    op.create_table('reserva_servicos',
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('preco_cobrado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantidade >= 1', name='ck_reserva_servicos_quantidade'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_adicionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserva_id', 'servico_id')
    )
    op.drop_table('tecnologias')
    op.drop_table('professores')
    op.drop_table('stacks')
    op.drop_table('professor_detalhes')
    op.drop_table('linguagens')
    op.drop_table('disciplinas')
    op.drop_table('tecnologia_linguagem')
    op.drop_table('disciplina_tecnologia')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplina_tecnologia',
    sa.Column('disciplina_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tecnologia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], name=op.f('disciplina_tecnologia_disciplina_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnologia_id'], ['tecnologias.id'], name=op.f('disciplina_tecnologia_tecnologia_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('disciplina_id', 'tecnologia_id', name=op.f('disciplina_tecnologia_pkey'))
    )
    op.create_table('tecnologia_linguagem',
    sa.Column('tecnologia_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('linguagem_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['linguagem_id'], ['linguagens.id'], name=op.f('tecnologia_linguagem_linguagem_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tecnologia_id'], ['tecnologias.id'], name=op.f('tecnologia_linguagem_tecnologia_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tecnologia_id', 'linguagem_id', name=op.f('tecnologia_linguagem_pkey'))
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semestre', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('professor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], name=op.f('disciplinas_professor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('disciplinas_pkey'))
    )
    op.create_table('linguagens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('linguagens_pkey')),
    sa.UniqueConstraint('nome', name=op.f('linguagens_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('professor_detalhes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sala', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('biografia', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('biografia_mapa', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], name=op.f('professor_detalhes_professor_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('professor_detalhes_pkey')),
    sa.UniqueConstraint('professor_id', name=op.f('professor_detalhes_professor_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('stacks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stacks_pkey')),
    sa.UniqueConstraint('nome', name=op.f('stacks_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('professores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('professores_pkey')),
    sa.UniqueConstraint('email', name=op.f('professores_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tecnologias',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stack_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], name=op.f('tecnologias_stack_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tecnologias_pkey')),
    sa.UniqueConstraint('nome', name=op.f('tecnologias_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('reserva_servicos')
    op.drop_table('avaliacoes')
    op.drop_table('reservas')
    op.drop_table('tarifas_temporada')
    op.drop_table('quartos')
    op.drop_table('hotel_comodidades')
    op.drop_table('hoteis')
    op.drop_table('usuarios')
    op.drop_table('servicos_adicionais')
    op.drop_table('comodidades')
    op.drop_table('cidades')
    # ### end Alembic commands ###
