import { useEffect, useState } from 'react'
import { listarCidades, listarHoteis, listarQuartosPorHotel, criarCidade, excluirCidade, criarHotel, excluirHotel, criarQuarto, excluirQuarto } from '../../services/api'
export default function PainelAdmin(){
 const [cidades,setCidades]=useState([]),[hoteis,setHoteis]=useState([]),[quartos,setQuartos]=useState([]),[erro,setErro]=useState('')
 const [cidade,setCidade]=useState({nome:'',estado:'CE'}),[hotel,setHotel]=useState({nome:'',cidade_id:'',categoria_estrelas:3}),[quarto,setQuarto]=useState({hotel_id:'',numero:'',tipo:'Standard',preco_diaria:100,max_adultos:2,max_criancas:0})
 async function load(){try{const [c,h]=await Promise.all([listarCidades(),listarHoteis()]);setCidades(c);setHoteis(h);let qs=[];for(const x of h) qs=qs.concat(await listarQuartosPorHotel(x.id));setQuartos(qs)}catch(e){setErro(e.message)}}
 useEffect(()=>{load()},[]); async function action(fn){setErro('');try{await fn();await load()}catch(e){setErro(e.message)}}
 return <div><h2 className="fs-4 mb-3">Painel Administrativo</h2>{erro&&<div className="alert alert-danger">{erro}</div>}<div className="row g-4">
 <div className="col-lg-4"><div className="card"><div className="card-body"><h5>Cidades</h5><input className="form-control mb-2" placeholder="Nome" value={cidade.nome} onChange={e=>setCidade({...cidade,nome:e.target.value})}/><input className="form-control mb-2" placeholder="UF" value={cidade.estado} onChange={e=>setCidade({...cidade,estado:e.target.value})}/><button className="btn btn-primary btn-sm mb-3" onClick={()=>action(()=>criarCidade(cidade))}>Cadastrar</button>{cidades.map(c=><div key={c.id} className="d-flex justify-content-between border-top py-2"><span>{c.nome}/{c.estado}</span><button className="btn btn-sm btn-outline-danger" onClick={()=>action(()=>excluirCidade(c.id))}>Excluir</button></div>)}</div></div></div>
 <div className="col-lg-4"><div className="card"><div className="card-body"><h5>Hotéis</h5><input className="form-control mb-2" placeholder="Nome" value={hotel.nome} onChange={e=>setHotel({...hotel,nome:e.target.value})}/><select className="form-select mb-2" value={hotel.cidade_id} onChange={e=>setHotel({...hotel,cidade_id:e.target.value})}><option value="">Cidade</option>{cidades.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select><select className="form-select mb-2" value={hotel.categoria_estrelas} onChange={e=>setHotel({...hotel,categoria_estrelas:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button className="btn btn-primary btn-sm mb-3" onClick={()=>action(()=>criarHotel(hotel))}>Cadastrar</button>{hoteis.map(h=><div key={h.id} className="d-flex justify-content-between border-top py-2"><span>{h.nome} ({h.categoria_estrelas}★)</span><button className="btn btn-sm btn-outline-danger" onClick={()=>action(()=>excluirHotel(h.id))}>Excluir</button></div>)}</div></div></div>
 <div className="col-lg-4"><div className="card"><div className="card-body"><h5>Quartos</h5><select className="form-select mb-2" value={quarto.hotel_id} onChange={e=>setQuarto({...quarto,hotel_id:e.target.value})}><option value="">Hotel</option>{hoteis.map(h=><option key={h.id} value={h.id}>{h.nome}</option>)}</select><input className="form-control mb-2" placeholder="Número" value={quarto.numero} onChange={e=>setQuarto({...quarto,numero:e.target.value})}/><input className="form-control mb-2" placeholder="Tipo" value={quarto.tipo} onChange={e=>setQuarto({...quarto,tipo:e.target.value})}/><input className="form-control mb-2" type="number" placeholder="Preço" value={quarto.preco_diaria} onChange={e=>setQuarto({...quarto,preco_diaria:Number(e.target.value)})}/><button className="btn btn-primary btn-sm mb-3" onClick={()=>action(()=>criarQuarto(quarto))}>Cadastrar</button>{quartos.map(q=><div key={q.id} className="d-flex justify-content-between border-top py-2"><span>#{q.numero} — R$ {Number(q.preco_diaria).toFixed(2)}</span><button className="btn btn-sm btn-outline-danger" onClick={()=>action(()=>excluirQuarto(q.id))}>Excluir</button></div>)}</div></div></div>
 </div></div>
}
