"""criacao inicial do banco

Revision ID: f51c62be188a
Revises: None
Create Date: 2026-08-30 19:27:15.956913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f51c62be188a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('limite_territorial', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comodidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('servicos_adicionais',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('preco >= 0', name='ck_servicos_preco'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hoteis',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cidade_id', sa.UUID(), nullable=False),
    sa.Column('categoria_estrelas', sa.Integer(), nullable=False),
    sa.Column('localizacao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('categoria_estrelas BETWEEN 1 AND 5', name='ck_hoteis_categoria_estrelas'),
    sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_comodidades',
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('comodidade_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comodidade_id'], ['comodidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id', 'comodidade_id')
    )
    op.create_table('quartos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('preco_diaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_adultos', sa.Integer(), nullable=False),
    sa.Column('max_criancas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('max_adultos >= 1', name='ck_quartos_max_adultos'),
    sa.CheckConstraint('max_criancas >= 0', name='ck_quartos_max_criancas'),
    sa.CheckConstraint('preco_diaria >= 0', name='ck_quartos_preco_diaria'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'numero', name='uq_quartos_hotel_numero')
    )
    op.create_table('tarifas_temporada',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('multiplicador', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.CheckConstraint('data_fim >= data_inicio', name='ck_tarifas_data'),
    sa.CheckConstraint('multiplicador > 0', name='ck_tarifas_multiplicador'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('quarto_id', sa.UUID(), nullable=False),
    sa.Column('data_checkin', sa.Date(), nullable=False),
    sa.Column('data_checkout', sa.Date(), nullable=False),
    sa.Column('quantidade_adultos', sa.Integer(), nullable=False),
    sa.Column('quantidade_criancas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('quantidade_bebes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('early_checkin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('late_checkout', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('necessita_berco', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tarifa_tipo', sa.String(length=20), server_default=sa.text("'Reembolsavel'"), nullable=False),
    sa.Column('data_limite_cancelamento', sa.Date(), nullable=True),
    sa.Column('valor_multa_cancelamento', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'Pendente'"), nullable=False),
    sa.CheckConstraint("status IN ('Pendente', 'Confirmada', 'Cancelada')", name='ck_reservas_status'),
    sa.CheckConstraint("tarifa_tipo IN ('Reembolsavel', 'Nao Reembolsavel')", name='ck_reservas_tarifa_tipo'),
    sa.CheckConstraint('data_checkout > data_checkin', name='ck_reservas_datas'),
    sa.CheckConstraint('quantidade_adultos >= 1', name='ck_reservas_adultos'),
    sa.CheckConstraint('quantidade_bebes >= 0', name='ck_reservas_bebes'),
    sa.CheckConstraint('quantidade_criancas >= 0', name='ck_reservas_criancas'),
    sa.CheckConstraint('valor_multa_cancelamento >= 0', name='ck_reservas_valor_multa'),
    sa.CheckConstraint('valor_total >= 0', name='ck_reservas_valor_total'),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('nota BETWEEN 1 AND 5', name='ck_avaliacoes_nota'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hoteis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id')
    )
    op.create_table('reserva_servicos',
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('preco_cobrado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantidade >= 1', name='ck_reserva_servicos_quantidade'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos_adicionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reserva_id', 'servico_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva_servicos')
    op.drop_table('avaliacoes')
    op.drop_table('reservas')
    op.drop_table('tarifas_temporada')
    op.drop_table('quartos')
    op.drop_table('hotel_comodidades')
    op.drop_table('hoteis')
    op.drop_table('usuarios')
    op.drop_table('servicos_adicionais')
    op.drop_table('comodidades')
    op.drop_table('cidades')
    # ### end Alembic commands ###
